#!/usr/bin/env python3
"""Convert blinker/assets/*.png into LVGL v9 C arrays (blinker/main/assets.c).

Usage:  python3 blinker/assets/convert_assets.py
Reads the PNGs, nearest-neighbor scales them to badge size (320x240 screen,
pixel-art stays crisp), and emits RGB565 (opaque) / RGB565A8 (alpha) images
in the exact `lv_image_dsc_t` layout LVGL v9 expects:
  RGB565A8 = w*h RGB565 pixels (LE) followed by w*h alpha bytes.

Stdlib only (minimal PNG decoder: 8-bit RGB/RGBA, non-interlaced).

Output sizes live in the table below; coordinates of the baked-in UI boxes
(measured from the PNG pixels, full-res -> half-res) are documented in
assets.h so the UI code can overlay dynamic bars/text exactly.
"""
import os
import struct
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
MAIN = os.path.join(os.path.dirname(HERE), 'main')


def decode_png(path):
    d = open(path, 'rb').read()
    assert d[:8] == b'\x89PNG\r\n\x1a\n', path
    pos = 8
    raw = b''
    while pos < len(d):
        ln = struct.unpack('>I', d[pos:pos + 4])[0]
        typ = d[pos + 4:pos + 8]
        chunk = d[pos + 8:pos + 8 + ln]
        if typ == b'IHDR':
            w, h, bitd, ctype, comp, filt, inter = struct.unpack('>IIBBBBB', chunk)
        elif typ == b'IDAT':
            raw += chunk
        pos += 12 + ln
    assert bitd == 8 and inter == 0, (path, bitd, inter)
    ch = {2: 3, 6: 4}[ctype]
    data = zlib.decompress(raw)
    stride = w * ch
    px = bytearray(w * h * ch)
    prev = bytearray(stride)
    p = 0
    for y in range(h):
        f = data[p]
        p += 1
        line = bytearray(data[p:p + stride])
        p += stride
        if f == 1:
            for i in range(ch, stride):
                line[i] = (line[i] + line[i - ch]) & 255
        elif f == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 255
        elif f == 3:
            for i in range(stride):
                a = line[i - ch] if i >= ch else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 255
        elif f == 4:
            for i in range(stride):
                a = line[i - ch] if i >= ch else 0
                b = prev[i]
                c = prev[i - ch] if i >= ch else 0
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 255
        elif f != 0:
            raise ValueError((path, 'filter', f))
        px[y * stride:(y + 1) * stride] = line
        prev = line
    if ch == 3:  # expand to RGBA
        rgba = bytearray(w * h * 4)
        for i in range(w * h):
            rgba[4 * i:4 * i + 3] = px[3 * i:3 * i + 3]
            rgba[4 * i + 3] = 255
        px = rgba
    return w, h, px


def scale_nearest(sw, sh, px, dw, dh):
    out = bytearray(dw * dh * 4)
    for y in range(dh):
        sy = min(sh - 1, y * sh // dh)
        for x in range(dw):
            sx = min(sw - 1, x * sw // dw)
            out[4 * (y * dw + x):4 * (y * dw + x) + 4] = px[4 * (sy * sw + sx):4 * (sy * sw + sx) + 4]
    return out


def to_rgb565(px):
    out = bytearray()
    for i in range(0, len(px), 4):
        r, g, b = px[i], px[i + 1], px[i + 2]
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        out += struct.pack('<H', v)
    return out


def convert(name, src, dw, dh, alpha):
    sw, sh, px = decode_png(os.path.join(HERE, src))
    if (dw, dh) != (sw, sh):
        px = scale_nearest(sw, sh, px, dw, dh)
    color = to_rgb565(px)
    if alpha:
        amap = bytes(px[i + 3] for i in range(0, len(px), 4))
        blob = color + amap
        cf = 'LV_COLOR_FORMAT_RGB565A8'
    else:
        blob = color
        cf = 'LV_COLOR_FORMAT_RGB565'
    assert len(blob) == (dw * dh * 3 if alpha else dw * dh * 2)
    print('%-16s %4dx%-4d %-22s %7d bytes' % (name, dw, dh, cf, len(blob)))
    return name, dw, dh, cf, blob


def emit_c(images):
    parts = []
    parts.append('// Auto-generated by blinker/assets/convert_assets.py — do not edit.')
    parts.append('// Pixel-art PNGs, nearest-neighbor scaled for the 320x240 badge LCD.')
    parts.append('#include "lvgl.h"')
    for name, w, h, cf, blob in images:
        parts.append('')
        parts.append('static const uint8_t %s_map[] = {' % name)
        for i in range(0, len(blob), 12):
            parts.append('    ' + ', '.join('0x%02x' % b for b in blob[i:i + 12]) + ',')
        parts.append('};')
        parts.append('')
        parts.append('const lv_image_dsc_t %s = {' % name)
        parts.append('    .header.magic = LV_IMAGE_HEADER_MAGIC,')
        parts.append('    .header.cf = %s,' % cf)
        parts.append('    .header.flags = 0,')
        parts.append('    .header.w = %d,' % w)
        parts.append('    .header.h = %d,' % h)
        parts.append('    .header.stride = %d,' % (w * 2))
        parts.append('    .data_size = %d,' % len(blob))
        parts.append('    .data = %s_map,' % name)
        parts.append('};')
    with open(os.path.join(MAIN, 'assets.c'), 'w') as f:
        f.write('\n'.join(parts) + '\n')


def main():
    images = [
        convert('assets_duel_bg', 'game-scene-bg-1.png', 320, 240, False),
        convert('assets_party_bg', 'party-background.png', 320, 240, False),
        convert('assets_menu_bg', 'main-menu.png', 320, 240, False),
        convert('assets_party_screen', 'party-screen.png', 320, 240, False),
        convert('assets_bubble', 'speech-bubble-1.png', 292, 129, True),
        convert('assets_speech_half', 'speech-bubble-1.png', 146, 64, True),
        convert('assets_caption', 'caption-bubble-1.png', 316, 64, True),
        convert('assets_caption_half', 'caption-bubble-half.png', 168, 64, True),
        convert('assets_slot', 'party-slot.png', 177, 36, True),
        convert('assets_cursor', 'cursor-1.png', 12, 26, True),
        convert('assets_cursor_white', 'cursor-white.png', 12, 26, True),
        convert('assets_cursor_sm', 'cursor-1.png', 8, 17, True),
    ]
    emit_c(images)
    total = sum(len(b) for _, _, _, _, b in images)
    print('total flash: %d bytes (%.1f KB)' % (total, total / 1024.0))


if __name__ == '__main__':
    main()
